language: cpp

branches:
  only:
    - master

compiler:
  - gcc

before_install:
  - sudo pip install cpp-coveralls

script:
  - scons test

after_success:
  - coveralls -b . -r . --gcov-options '\-lp'
