env = Environment()
env.Append(CPPPATH='include')
env.Append(CCFLAGS='-ansi')
env.Append(CCFLAGS='-pedantic')
env.Append(CCFLAGS='-Weffc++')
env.Append(CCFLAGS='-Wall')
env.Append(CCFLAGS='-Werror')
env.Append(CCFLAGS='-Wextra')
env.Append(CCFLAGS='-O0')
env.Append(CCFLAGS='-fprofile-arcs')
env.Append(CCFLAGS='-ftest-coverage')
env.Append(CCFLAGS='-fno-exceptions')
env.Append(CCFLAGS='-fno-rtti')
env.Append(LINKFLAGS='--coverage')
env.Clean('test', 'tests/test.gcno')
env.Clean('test', 'tests/test.gcda')

program = env.Program('test', 'tests/test.cpp')
env.Default(program)
env.Alias('test', program, program[0].abspath)
